### PR TITLE
lab1

### PR DESCRIPTION
**Pull request by shanse11**

### CODE REVIEW

**Review by zjpedu — CHANGES_REQUESTED** [review]
Please delete the redundant files.

**Review by zjpedu — APPROVED** [review]
LGTM

**Comment by shanse11** [comment]
助教您好，我这里遇到了一点问题，不知道怎么删除那个
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zjpedu/Computer-Systems-Labs"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月14日(星期三) 晚上9:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zjpedu/Computer-Systems-Labs] lab1 (PR #45)





 
@zjpedu requested changes on this pull request.
 
Please delete the redundant files.

**Comment by zjpedu** [comment]
you can use the following steps:
```shell
rm - f delete_file_name
git add delete_file_name
git commit -m "delete file"
git push
```

**Comment by zjpedu** [comment]
Actually, I already delete the file in my repo. So you don't need open a pull request into my repo. Thanks.

**Pull request merged**
